<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\SimsConverter.Domain\SimsConverter.Domain.csproj" />
    <ProjectReference Include="..\SimsConverter.Package\SimsConverter.Package.csproj" />
    <ProjectReference Include="..\SimsConverter.Textures\SimsConverter.Textures.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
