<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SimsConverter.Domain\SimsConverter.Domain.csproj" />
    <ProjectReference Include="..\SimsConverter.Package\SimsConverter.Package.csproj" />
  </ItemGroup>
</Project>
